#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
$HOME/.config/polybar/launch.sh &
nm-applet &
picom &
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          10

#bspc config top_padding			38
bspc config bottom_padding		0
bspc config left_padding		0
bspc config right_padding		0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

# Start flavours
bspc config normal_border_color		      '#353535'
bspc config active_border_color	          '#303030'
bspc config focused_border_color	      '#82AAFF'
bspc config presel_feedback_color	      '#82AAFF'
bspc config urgent_border_color 	      '#F07178'
# End flavours

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2' follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Brave-browser desktop='^2' follow=on
bspc rule -a vlc desktop='^10' follow=on
bspc rule -a Pcmanfm desktop='^3' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

wmname LG3D
